# Generated by Django 3.2.4 on 2022-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disrticts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=120)),
                ('Population', models.PositiveIntegerField()),
                ('Fdv_rate', models.PositiveIntegerField()),
                ('Sdv_rate', models.PositiveIntegerField()),
            ],
        ),
    ]
