# Generated by Django 3.2.4 on 2022-02-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disrticts',
            new_name='Districts',
        ),
    ]
