# Generated by Django 4.0.2 on 2022-02-28 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0003_books_images'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('order_placed', 'order_placed'), ('incart', 'incart')], default='incart', max_length=120),
        ),
        migrations.CreateModel(
            name='My_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('Intransit', 'Intransit'), ('cancel', 'cancel'), ('Dispatched', 'Dispatched'), ('delivered', 'delivered')], default='order_placed', max_length=120)),
                ('excepted_delivery_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
