# Generated by Django 4.0.2 on 2022-03-03 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_my_orders_address_alter_carts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('incart', 'incart'), ('order_placed', 'order_placed')], default='incart', max_length=120),
        ),
        migrations.AlterField(
            model_name='my_orders',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='my_orders',
            name='status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('Intransit', 'Intransit'), ('order_placed', 'order_placed'), ('Dispatched', 'Dispatched'), ('delivered', 'delivered')], default='order_placed', max_length=120),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=250)),
                ('profile_pic', models.ImageField(upload_to='image')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
